### ISSUE TITLE
Falta estructura o sobren paràgrafs

### ISSUE THREAD

**Issue by IgnasiLucas** [R-mario/populy#3]
Les seccions d'Introducció i d'alfabetització informàtica són molt massives. Es fan llargues. Potser si distribuires les idees en subseccions seria més clar. Dóna la sensasió de què vols encabir moltes idees. Potser falta passar la tisora i eliminar algunes coses per facilitar la lectura i ressaltar allò que consideres més important. 

Quant a l'estructura, a mi, personalment, m'agraden més les seccions numerades. Així és més fàcil recordar en quin apartat estàs. Per cert, veig que els enllaços a les seccions no funcionen, veritat? No he trobat la manera d'arreglar-ho.

**Comment by R-mario** [comment]
- Introducción: se ha añadido una subsección llamada "estado del arte" donde se explica el funcionamiento de populus y sus deficiencias, con el objetivo de hacer una introducción mejor estructurada.
- Alfabetización informática: se ha cambiado el nombre por alfabetización computacional y se han eliminado un par de párrafos para resaltar solo los aspectos de la "computer literacy"
- Las secciones están numeradas

- [x] - Los enlaces internos siguen sin funcionar
